packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@auth/core": 0.37.2
  "@paralleldrive/cuid2": 2.2.2
  "@remixicon/react": 4.6.0
  "@t3-oss/env-core": 0.12.0
  "@t3-oss/env-nextjs": 0.12.0
  "@tanstack/react-query": 5.69.0
  "@trpc/client": 11.1.0
  "@trpc/react-query": 11.1.0
  "@trpc/server": 11.1.0
  "@trpc/tanstack-react-query": 11.1.0
  clsx: 2.1.1
  date-fns: 4.1.0
  dotenv-cli: 8.0.0
  eslint: 9.25.1
  es-toolkit: 1.32.0
  framer-motion: 12.9.4
  lucide-react: 0.483.0
  moment: 2.29.4
  nanoid: 5.1.5
  neverthrow: 8.2.0
  next: 15.3.1
  next-auth: 5.0.0-beta.25
  prettier: 3.5.3
  server-only: 0.0.1
  socket.io: 4.7.4
  socket.io-client: 4.7.4
  speakeasy: 2.0.0
  superjson: 2.2.1
  tailwind-merge: 3.1.0
  typescript: 5.8.3
  uuid: 10.0.0
  "@types/uuid": 10.0.0
  zod: 3.24.2

catalogs:
  tailwind3:
    tailwindcss: 3.4.17
  tailwind4:
    "@tailwindcss/postcss": 4.1.3
    tailwindcss: 4.1.3
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.12
    "@types/react-dom": 19.0.4

onlyBuiltDependencies:
  - esbuild
